name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # What's Changed
  $CHANGES
categories:
  - title: ':boom: Breaking Changes'
    label: 'breaking change'
  - title: ':rocket: New Features'
    label: 'new feature'
  - title: ':bug: Bug Fixes'
    label: 'bug'
  - title: ':sparkles: Enhancement'
    label: 'enhancement'
  - title: ':wrench: Maintenance'
    label: 'maintenance'
  - title: ':book: Documentation'
    label: 'documentation'
  - title: ':shield: Security'
    label: 'security fix'
  - title: ':gear: Dependency Updates'
    label: 'dependencies'
  - title: ':package: Packages'
    label: 'packages'
  - title: ':twisted_rightwards_arrows: Integrations'
    label: 'integrations'
  - title: ':electric_plug: Plugins'
    label: 'plugins'

version-resolver:
  major:
    labels:
      - 'breaking change'
  minor:
    labels:
      - 'new feature'
      - 'enhancement'
  patch:
    labels:
      - 'bug'
      - 'maintenance'
      - 'documentation'
      - 'dependencies'
      - 'security'

exclude-labels:
  - 'skip-changelog'
